name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  python-ci:
    if: github.repository != 'stillsystems/still-systems-template'
    uses: stillsystems/.github/.github/workflows/reusable-python-ci.yml@main
    with:
      python-version: '3.12'
